/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    experiences: Experience;
    skills: Skill;
    education: Education;
    media: Media;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    profile: Profile;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    profile: ProfileSelect<false> | ProfileSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Case studies. Save drafts freely; publishing requires the full case study and content confirmation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Lowercase kebab-case, used in /projects/<slug>. Generated from the title when empty.
   */
  slug: string;
  /**
   * One or two sentences: the problem and your contribution.
   */
  summary: string;
  category: 'ai-workflows' | 'data-infrastructure' | 'product-engineering' | 'research';
  projectType: 'professional' | 'personal' | 'academic';
  /**
   * Text only. Logos are not shown.
   */
  organization?: string | null;
  experience?: (number | null) | Experience;
  /**
   * Your role on this project.
   */
  role: string;
  startMonth?: string | null;
  endMonth?: string | null;
  /**
   * The problem, users, and constraints.
   */
  context: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * What you personally did, separate from the team.
   */
  contribution: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Technical choices and their tradeoffs.
   */
  decisions: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Narrative result. Numbers are optional.
   */
  outcome: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. Only add numbers whose context you can state.
   */
  metrics?:
    | {
        valueText: string;
        label: string;
        /**
         * What was measured, when, and against what baseline.
         */
        context: string;
        sourceNote?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Unpublished skills are hidden from public pages.
   */
  technologies?: (number | Skill)[] | null;
  /**
   * Optional. Leave empty rather than using a placeholder.
   */
  cover?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        /**
         * Say whether a diagram is conceptual or the actual architecture.
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Only add links that exist and are public.
   */
  links?:
    | {
        kind: 'source' | 'demo' | 'article';
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Defaults to the project title.
     */
    title?: string | null;
    /**
     * Defaults to the summary.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Show on the homepage. At most 3 published.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first. Ties are ordered by ID.
   */
  sortOrder: number;
  /**
   * Editorial confirmation required to publish. It does not control who can see the entry.
   */
  contentReady?: boolean | null;
  /**
   * Where the facts come from. Never shown publicly.
   */
  internalSource?: string | null;
  /**
   * Open questions and publication notes. Never shown publicly.
   */
  internalNotes?: string | null;
  mediaRefs?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One entry per company. Add freelance and full-time periods as separate engagements.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  organization: string;
  location?: string | null;
  workMode?: ('remote' | 'hybrid' | 'onsite') | null;
  /**
   * Newest first. The homepage shows the first engagement.
   */
  engagements: {
    role: string;
    employmentType: 'full-time' | 'part-time' | 'contract' | 'freelance' | 'internship';
    startMonth: string;
    endMonth?: string | null;
    isCurrent?: boolean | null;
    summary?: string | null;
    /**
     * The first contribution appears on the homepage.
     */
    contributions?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Unpublished skills are hidden from public pages.
     */
    technologies?: (number | Skill)[] | null;
    /**
     * For concurrent engagements, e.g. "Concurrent with Offerland freelance engagement".
     */
    overlapNote?: string | null;
    id?: string | null;
  }[];
  /**
   * Lower numbers appear first. Ties are ordered by ID.
   */
  sortOrder: number;
  /**
   * Editorial confirmation required to publish. It does not control who can see the entry.
   */
  contentReady?: boolean | null;
  /**
   * Source of these facts and unpublished caveats. Never shown publicly.
   */
  internalSource?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Names grouped by domain. No ratings or percentages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  name: string;
  group: 'languages-frameworks' | 'ai' | 'backend' | 'data' | 'messaging' | 'infrastructure';
  /**
   * Lower numbers appear first. Ties are ordered by ID.
   */
  sortOrder: number;
  /**
   * Editorial confirmation required to publish. It does not control who can see the entry.
   */
  contentReady?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Files are private by default. Public files are only served when marked ready and referenced by published content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what the image shows. Required for images unless marked decorative.
   */
  alt?: string | null;
  /**
   * Decorative images have empty alt text and cannot be used as covers.
   */
  decorative?: boolean | null;
  caption?: string | null;
  /**
   * Friendly name used when the file is downloaded, e.g. Vincent-Siauw-CV.pdf.
   */
  downloadName?: string | null;
  kind?: ('image' | 'pdf') | null;
  visibility: 'private' | 'public';
  contentReady?: boolean | null;
  /**
   * Never shown publicly.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education".
 */
export interface Education {
  id: number;
  institution: string;
  qualification: string;
  field: string;
  startYear: number;
  endYear: number;
  /**
   * Optional. Shown on the About page only.
   */
  gpa?: string | null;
  thesisTitle?: string | null;
  notes?: string | null;
  /**
   * Lower numbers appear first. Ties are ordered by ID.
   */
  sortOrder: number;
  /**
   * Editorial confirmation required to publish. It does not control who can see the entry.
   */
  contentReady?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Created automatically when a published project slug changes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  fromPath: string;
  toPath: string;
  project: number | Project;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'education';
        value: number | Education;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  category?: T;
  projectType?: T;
  organization?: T;
  experience?: T;
  role?: T;
  startMonth?: T;
  endMonth?: T;
  context?: T;
  contribution?: T;
  decisions?: T;
  outcome?: T;
  metrics?:
    | T
    | {
        valueText?: T;
        label?: T;
        context?: T;
        sourceNote?: T;
        id?: T;
      };
  technologies?: T;
  cover?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  links?:
    | T
    | {
        kind?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  featured?: T;
  sortOrder?: T;
  contentReady?: T;
  internalSource?: T;
  internalNotes?: T;
  mediaRefs?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  organization?: T;
  location?: T;
  workMode?: T;
  engagements?:
    | T
    | {
        role?: T;
        employmentType?: T;
        startMonth?: T;
        endMonth?: T;
        isCurrent?: T;
        summary?: T;
        contributions?:
          | T
          | {
              text?: T;
              id?: T;
            };
        technologies?: T;
        overlapNote?: T;
        id?: T;
      };
  sortOrder?: T;
  contentReady?: T;
  internalSource?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  group?: T;
  sortOrder?: T;
  contentReady?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education_select".
 */
export interface EducationSelect<T extends boolean = true> {
  institution?: T;
  qualification?: T;
  field?: T;
  startYear?: T;
  endYear?: T;
  gpa?: T;
  thesisTitle?: T;
  notes?: T;
  sortOrder?: T;
  contentReady?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  decorative?: T;
  caption?: T;
  downloadName?: T;
  kind?: T;
  visibility?: T;
  contentReady?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toPath?: T;
  project?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Identity, hero copy, bio, and contact details.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: number;
  displayName: string;
  roleLabel: string;
  heroHeading: string;
  /**
   * Two sentences at most.
   */
  heroIntro: string;
  location?: string | null;
  /**
   * Shown on the homepage.
   */
  shortBio?: string | null;
  /**
   * Shown on the About page.
   */
  fullBio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional. Leave empty unless current.
   */
  availabilityText?: string | null;
  relocationText?: string | null;
  spokenLanguages?:
    | {
        name: string;
        proficiency: string;
        id?: string | null;
      }[]
    | null;
  email: string;
  socialLinks?:
    | {
        kind: 'github' | 'linkedin' | 'other';
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload the public version (no phone number). The download button is hidden until this is set.
   */
  resume?: (number | null) | Media;
  /**
   * Editorial confirmation required to publish. It does not control who can see the entry.
   */
  contentReady?: boolean | null;
  mediaRefs?: (number | Media)[] | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  defaultSeoTitle: string;
  defaultSeoDescription: string;
  /**
   * Optional. A simple generated image with name and title is used when empty.
   */
  socialImage?: (number | null) | Media;
  footerText?: string | null;
  /**
   * Editorial confirmation required to publish. It does not control who can see the entry.
   */
  contentReady?: boolean | null;
  mediaRefs?: (number | Media)[] | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  displayName?: T;
  roleLabel?: T;
  heroHeading?: T;
  heroIntro?: T;
  location?: T;
  shortBio?: T;
  fullBio?: T;
  availabilityText?: T;
  relocationText?: T;
  spokenLanguages?:
    | T
    | {
        name?: T;
        proficiency?: T;
        id?: T;
      };
  email?: T;
  socialLinks?:
    | T
    | {
        kind?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  resume?: T;
  contentReady?: T;
  mediaRefs?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  defaultSeoTitle?: T;
  defaultSeoDescription?: T;
  socialImage?: T;
  footerText?: T;
  contentReady?: T;
  mediaRefs?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}