/* Generated by Payload, with one project change: POST is wrapped so version restores are drafts (AC-12). */
import config from '@payload-config'
import '@payloadcms/next/css'
import {
  REST_DELETE,
  REST_GET,
  REST_OPTIONS,
  REST_PATCH,
  REST_POST,
  REST_PUT,
} from '@payloadcms/next/routes'

import { withDraftRestore } from '@/lib/payload-rest'

export const GET = REST_GET(config)
export const POST = withDraftRestore(REST_POST(config))
export const DELETE = REST_DELETE(config)
export const PATCH = REST_PATCH(config)
export const PUT = REST_PUT(config)
export const OPTIONS = REST_OPTIONS(config)
